# Hexo Configuration Hexo配置
## Docs: https://hexo.io/docs/configuration.html 文档：https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/ 来源:https://github.com/hexojs/hexo/

# Site 地点
# 网站标题
title: 天火流光
# 网站副标题
subtitle: 天火流光的小屋
# 网站描述
description: 一个人静静坐在电脑面前写代码的感觉，那是什么感觉?那是武林高手闭关修炼的感觉。
# 搜索关键词
keywords: '天火流光 ,博客, 前端 '
# 名字
author: 天火流光
# 网站使用的语言
language:  zh-Hans
# 网站时区
timezone: 'Asia/Shanghai'

# URL 网址
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
## 如果您的站点放在子目录中，将url设置为“http://yoursite.com/child”，将根目录设置为“/child/”
# 网址
url: https://GuoChen-thlg.github.io  #github
#url: https://thlg.gitee.io/  #码云
# 根
root: /
# 永久链接
permalink: :year/:month/:day/:title/:abbrlink/
# 永久链接的默认值
permalink_defaults:
# 漂亮的网址
pretty_urls:           #设置为false，从permalinks中删除尾随的index.html
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory 目录
# 源
source_dir: source
# 公共
public_dir: public
# 标记
tag_dir: tags
# 存档
archive_dir: archives
# 种类
category_dir: categories
# 代码
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: :lang
# 跳过渲染
skip_render: README.md

# 文章
new_post_name: :title.md # File name of new posts 新帖子的文件名
#默认
default_layout: post
# 在中文和英文之间加入空格
auto_spacing: true
#首字母大写
titlecase: false # Transform title into titlecase 将网站标题转换为首字母大写
#外部连接
external_link:
  enable: true # Open external links in new tab 在新选项卡中打开外部链接
  field: site # Apply to the whole site 适用于整个网站
#  排除
  exclude: ''
# 文件名  把文件名称转换为"1"小写或"2"大写
filename_case: 0
# 渲染草稿
render_drafts: false
# 文章资源文件夹
post_asset_folder: false
# 相对连接
relative_link: false
# 显示未来的文章
future: true

# 代码高亮量
highlight:
  enable: true
# 行号
  line_number: true
# 自动检测语言
  auto_detect: false
# 标签代替
  tab_replace: ''

# Home page setting主页设置
# path: Root path for your blogs index page. (default = '')
# 路径:博客索引页的根路径。(default= '')
# per_page: Posts displayed per page. (0 = disable pagination)
# 每页：每页显示的帖子。(0 =禁用分页)
# order_by: Posts order. (Order by date descending by default)
# 排序:发布订单。(默认按日期降序排列)
index_generator:
# 路径 博客主页根路径
  path: ''
# 每页 每页展示文章数量 (0 = 关闭分页功能)
  per_page: 10
# 排序 排序，默认按时间降序排列
  order_by: -date

# Category & Tag 分类和标签
# 默认分类
default_category: uncategorized
# 分类别名
category_map:
# 标签别名	
tag_map:


# Metadata elements数据元素

## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format日期/时间格式

## Hexo uses Moment.js to parse and display date
## Hexo使用Moment.js解析和显示日期
## You can customize the date format as defined in
## 您可以自定义定义的日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

## Use post's date for updated date unless set in front-matter
## 使用更新日期的邮政日期，除非在前面的事项设置
use_date_for_updated: false

# 分页 Pagination
## Set per_page to 0 to disable pagination
## 将per_page设置为0以禁用分页
# 每页
per_page: 10
# 分页
pagination_dir: page

# Include / Exclude file(s) 包含/排除文件
## include:/exclude: options only apply to the 'source/' folder
## 包括排除:/选项只适用于'源/'文件夹
include:
exclude:
ignore:

#  扩展 Extensions
## 插件 Plugins: https://hexo.io/plugins/
## 主题 Themes: https://hexo.io/themes/
theme: next #  next

# 部署 Deployment
## 文档说明 Docs: https://hexo.io/docs/deployment.html
# 配置
deploy:
# 类型
  type: git
# 仓库
  repository:
    github: https://github.com/GuoChen-thlg/GuoChen-thlg.github.io.git,master
    coding: https://gitee.com/thlg/thlg.git,master
  #repo: https://github.com/GuoChen-thlg/GuoChen-thlg.github.io.git
# 仓库分支
  #branch: master

# 头像  
avatar: /uploads/tx.jpg

feed: # RSS订阅插件
  type: atom
  path: atom.xml
  limit: 0

plugins: hexo-generate-feed

# 站点内容搜索
 # search:  
 # path: search.xml
 # field: post
 # format: html
 # limit: 10000

# Live2D
## https://github.com/xiazeyu/live2d-widget.js
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  enable: true
  #scriptFrom: local
  #pluginRootPath: live2dw/
  #pluginJsPath: lib/
  pluginModelPath: assets/
  #tagMode: true
  #debug: false
  model:
  scale: 1  # 比例
  use: live2d-widget-model-shizuku  # 下载的动画模型名称  shizuku
  display:
    position: right    # 模型在网页显示位置
    width: 200
    height: 350
  mobile:
    show: false  # 移动设备是否显示
    scale: 0.5 # 比例
  dev:
    border: false #在canvas周围显示边界
  dialog:
    enable: true  #显示人物对话框
    hitokoto: true #使用一言API
    
# hexo-neat
neat_enable: true
 
neat_html:
  enable: true
  exclude:
  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
 
neat_js:
  enable: true
  mangle: false
  output:
  compress:
  exclude:
    - '*.min.js'